//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TaskListAPI {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ResTaskListAPI {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResTaskListAPI() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TaskListAPI.ResTaskListAPI", typeof(ResTaskListAPI).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All customers retrieved..
        /// </summary>
        internal static string All_customers_retrieved_ {
            get {
                return ResourceManager.GetString("All_customers_retrieved_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Created new customer with id {0}..
        /// </summary>
        internal static string Created_new_customer_with_id__0__ {
            get {
                return ResourceManager.GetString("Created_new_customer_with_id__0__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer with id {0} not found..
        /// </summary>
        internal static string Customer_with_id__0__not_found_ {
            get {
                return ResourceManager.GetString("Customer_with_id__0__not_found_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer with id {0} retrieved..
        /// </summary>
        internal static string Customer_with_id__0__retrieved_ {
            get {
                return ResourceManager.GetString("Customer_with_id__0__retrieved_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer with name {0} already exists..
        /// </summary>
        internal static string Customer_with_name__0__already_exists_ {
            get {
                return ResourceManager.GetString("Customer_with_name__0__already_exists_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Database concurrency error..
        /// </summary>
        internal static string Database_concurrency_error_ {
            get {
                return ResourceManager.GetString("Database_concurrency_error_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Begin request .
        /// </summary>
        internal static string LoggingMiddleware_Invoke_Begin_request_ {
            get {
                return ResourceManager.GetString("LoggingMiddleware_Invoke_Begin_request_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End request .
        /// </summary>
        internal static string LoggingMiddleware_Invoke_End_request_ {
            get {
                return ResourceManager.GetString("LoggingMiddleware_Invoke_End_request_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Removed customer with id {0}..
        /// </summary>
        internal static string Removed_customer_with_id__0__ {
            get {
                return ResourceManager.GetString("Removed_customer_with_id__0__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server error..
        /// </summary>
        internal static string Server_error_ {
            get {
                return ResourceManager.GetString("Server_error_", resourceCulture);
            }
        }
    }
}
