---
apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: "{{ source_branch }}"
  annotations:
    pipelinesascode.tekton.dev/on-event: "[pull_request]"
    pipelinesascode.tekton.dev/on-target-branch: "main"
    pipelinesascode.tekton.dev/task: "[git-clone, github-add-comment, https://github.com/Ortec-Finance/pac-commons/blob/main/Tasks/build-csharp.yaml]"
    pipelinesascode.tekton.dev/pipeline: "https://github.com/Ortec-Finance/pac-commons/blob/main/Pipelines/build-csharp.yaml"
    pipelinesascode.tekton.dev/max-keep-runs: "5"
    pipelinesascode.tekton.dev/target-namespace: "pac-pipelines"
spec:
  params:
    # The variable with brackets are special to Pipelines as Code.
    # They will automatically be expanded with the events from Github.
    - name: repo-url
      value: "{{ repo_url }}"
    - name: revision
      value: "{{ revision }}"
    - name: pull-request-number
      value: "{{ pull_request_number }}"
    - name: application-name
      value: tasklist-api
    - name: application-imageurl
      value: image-registry.openshift-image-registry.svc:5000/csharp/demo-app:{{ source_branch }}
    - name: perform-unit-test
      value: 'true'
  pipelineRef:
    name: build-csharp
  workspaces:
    - name: test-results-pvc
      persistentVolumeClaim:
        claimName: azfiles-test-results
    - name: source-pvc
      volumeClaimTemplate:
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 2Gi
    # This workspace will inject secret to help the git-clone task to be able to
    # checkout the private repositories
    - name: basic-auth
      secret:
        secretName: "{{ git_auth_secret }}"
